
from enum import Enum

class HeightmapType(Enum):
    MOTION_BLOCKING = "MOTION_BLOCKING"
    MOTION_BLOCKING_NO_LEAVES = "MOTION_BLOCKING_NO_LEAVES"
    OCEAN_FLOOR = "OCEAN_FLOOR"
    OCEAN_FLOOR_WG = "OCEAN_FLOOR_WG"
    WORLD_SURFACE = "WORLD_SURFACE"
    WORLD_SURFACE_WG = "WORLD_SURFACE_WG"
    